#!/usr/bin/env bash

UNAMEOUT="$(uname -s)"

WHITE='\033[1;37m'
NC='\033[0m'

# Verify operating system is supported...
case "${UNAMEOUT}" in
    Linux*)             MACHINE=linux;;
    Darwin*)            MACHINE=mac;;
    *)                  MACHINE="UNKNOWN"
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo "Unsupported operating system [$(uname -s)]. Laravel Sail supports macOS, Linux, and Windows (WSL2)." >&2

    exit 1
fi

# Source the ".env" file so symfony environment variables are available...
if [ -f ./api/.env ]; then
    source ./api/.env
fi

# Define environment variables...
export APP_PORT=${APP_PORT:-80}
export APP_SERVICE=${APP_SERVICE:-"php"}
export DB_PORT=${DB_PORT:-3306}
export WWWUSER=${WWWUSER:-$UID}
export WWWGROUP=${WWWGROUP:-$(id -g)}
export EXEC_CMD="exec"

if [ -z "${DOYO_CI}" ]; then
    export DOYO_CI=0;
fi

if [[ 1 == "${DOYO_CI}" ]]; then
    export EXEC_CMD="exec -T"
fi

# Function that outputs Sail is not running...
function yawik_is_not_running {
    echo -e "${WHITE}Sail is not running.${NC}" >&2
    echo "" >&2
    echo -e "${WHITE}You may Sail using the following commands:${NC} './yawik up' or './yawik up -d'" >&2

    exit 1
}

# Source the ".env" file so symfony environment variables are available...
if [ -f ./.env ]; then
    source ./.env
fi
if [ -z "${API_PLATFORM_ENV}" ]; then
    API_PLATFORM_ENV="dev"
fi

if [ -f ./.env ]; then
    source ./.env
fi

# start handling command args
COMPOSE_FILE="-f docker-compose.yml -f docker-compose.${API_PLATFORM_ENV}.yml"

if [ $# -gt 0 ]; then
    if [ "$1" == "build" ]; then
        echo -e "${WHITE}Build container images${NC}"
        docker-compose $COMPOSE_FILE build "${@: 2}"
    elif [ "$1" == "boot" ]; then
        echo -e "${WHITE}Booting up yawik ...${NC}"
        docker-compose $COMPOSE_FILE build "${@: 2}"
        docker-compose $COMPOSE_FILE up "${@: 2}"
    elif [ "$1" == "up" ]; then
        echo -e "${WHITE}Running api-platform in development mode${NC}"
        docker-compose ${COMPOSE_FILE} up "${@: 2}"
    elif [[ "$1" == "require" || "$1" == "req" ]]; then
        docker-compose $EXEC_CMD php composer require "${@: 2}"
    elif [ "$1" == "remove" ]; then
        docker-compose $EXEC_CMD php composer remove "${@: 2}"
    elif [ "$1" == "composer" ]; then
        docker-compose $EXEC_CMD php "${@: 1}"
    elif [[ "$1" == "sf" || "$1" == "symfony" ]]; then
        docker-compose $EXEC_CMD php bin/console "${@: 2}"
    elif [[ "$1" == "psalm" ]]; then
        docker-compose $EXEC_CMD php ./vendor/bin/psalm "${@: 2}"
    elif [[ "$1" == "csfix" ]]; then
        docker-compose $EXEC_CMD php ./vendor/bin/php-cs-fixer "${@: 2}"
    elif [[ "$1" == "phpspec" ]]; then
        docker-compose $EXEC_CMD php ./vendor/bin/phpspec "${@: 2}"
    elif [[ "$1" == "phpunit" ]]; then
        docker-compose $EXEC_CMD php ./vendor/bin/phpunit "${@: 2}"
    elif [[ "$1" == "cache:clear" ]]; then
        docker-compose $EXEC_CMD php bin/console cache:clear "${@: 2}"
    elif [[ "$1" == "doctrine" ]]; then
        docker-compose $EXEC_CMD php bin/console "${@: 2}"
    else
        docker-compose "$@"
    fi
else
    docker-compose ps
fi
