api_platform:
  title: Yawik API
  version: 1.0.0
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  # Mercure integration, remove if unwanted
  mercure: ~
  # Good cache defaults for REST APIs
  doctrine_mongodb_odm:
    enabled: true
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
  collection:
    pagination:
      items_per_page: 5
