name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch: ~

env:
  DOYO_CI: 1

jobs:
  build:
    name: Build (Build Docker Image)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/docker-compose.yml','**/docker-compose.dev.yml','**/api/Dockerfile','**/pwa/Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Start services
        run: ./dev boot -d
      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(./dev ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy)
                ./dev ps
                ./dev logs
                exit 1
              ;;
            esac
          done
          exit 1
      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost
      - name: Check HTTPS reachability
        run: curl  -vk -o /dev/null https://localhost
      - name: Lists existing image
        run: docker image ls
        continue-on-error: true
      - name: Push image
        run: |
          docker push ghcr.io/kilip/yawik-php-dev
          docker push ghcr.io/kilip/yawik-caddy-dev
          docker push ghcr.io/kilip/yawik-nuxt-dev
      #- name: Create test database
      #  run: |
      #    ./dev symfony -e test yawik:fixtures:load
      #- name: PHPUnit
      #  run: ./dev phpunit
      #- name: Doctrine Schema Validator
      #  run: docker-compose exec -T php bin/console doctrine:schema:validate --skip-sync
      #- name: Jest
      #  run: docker-compose exec -T pwa yarn test --ci --passWithNoTests
