<?php

/*
 * This file is part of the Yawik project.
 *
 * (c) 2013-2021 Cross Solution
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Yawik\Testing;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase as BaseTestCase;
use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\Client;
use Symfony\Contracts\HttpClient\ResponseInterface;

class ApiTestCase extends BaseTestCase
{
    protected static function createClient(array $kernelOptions = [], array $defaultOptions = []): Client
    {
        $defaultOptions = [
            'headers' => ['accept' => ['application/json']],
        ];

        return parent::createClient($kernelOptions, $defaultOptions); // TODO: Change the autogenerated stub
    }

    protected function get(string $uri, array $options = []): ResponseInterface
    {
        return static::createClient()->request('GET', $uri, $options);
    }
}
